### ISSUE TITLE
RFC2 comments - points of confusion

### ISSUE THREAD

**Issue by mcdittmar** [ivoa-std/CoordinateDM#9]
Points of confusion for me:

**Section 2.1.1 (and similar):** 
It is not clear to me what the distinction is between "pixel domain" and "physical domain". After reading the whole document, I suspect that perhaps "pixel domain" is where measured quantities that are NOT physical coordinates (like magnitude, flux, etc.) live, but it is not at all clear to me how to treat non-physical measurements in the context of this model. Perhaps they are not supposed to be - by working back and forth between this and the measurements model, it begins to make some sense in the abstract, at least. If that is the intention, then a clear statement early on describing the relationship between the two models for physical quantities would be helpful to the novice. For example, in the second bullet of section 1.2, a reference to the appropriate subsection for defining the physical coordinate axis followed by a reference to the Measurement Model for defining value and error might help to underline the need to consult both models simultaneously for the complete picture.

**Section 4.8, item 2:**
- I don't disagree with the statement beginning "It is a bad idea...", but I don't see how quoting the ISO time format for UTC mitigates the problem, especially in light of the lack of a time scale for JD and MJD. The implication seems to be that M/JD should simply be converted to resemble the ISO 8601 format. Is that the intention? Doesn't that amount to "Don't use M/JD at all?", or worse "Don't tell us you used M/JD, just make it look like UTC?"
- The text refers to the "restricted form of ISO 8601". If this is intended to refer to the subset defined by IETF RFC 3339 (https://datatracker.ietf.org/doc/html/rfc3339), then the format given is problematic - the restricted form does not allow for extended years with signs or more than 4 digits. If it is not intended to refer to that RFC, then it is probably better not to refer to it as "the restricted form of ISO 8601". Something like "Instead, use a subset of the ISO 8601 form ... with no time zone indicators" would be sufficient (and cover the cases of both time zone characters and numeric offsets indicating time zones).

**Section 4.8, item 6:**
- The string beginning "Because TDB runs..." is not a sentence and I'm not sure whether the intended statement that all this qualifies is missing, or if perhaps "which" should be "it".
- There is a reference to "the above cited A&A paper", but no "A&A paper" is mentioned by that designation prior to this point in the text. I suspect this should be replaced by the citation "Rots, et al. (2015)" (or perhaps "Rots and Bunclark et al, 2015", as cited in the opening of section 4.8.)

**Section 4.13.1:** 
TimeOffset is a real quantity, but does not appear to have an associated unit of measure in the model. This is probably part of my general "units of measure" confusion, but it leads me to wonder: Is there a reason why this is required to be a real number and not an ISO 8601 time interval? Section 4.8 seems to be directing users to use the ISO 8601 format for all types of time measurements, so an ISO interval would seem to be a more natural way of stating an offset, and would avoid the units issue entirely, of course.

**Comment by mcdittmar** [comment]
>Section 2.1.1: distinction is between "pixel domain" and "physical domain".

I'd appreciate a suggestion on where/how to help clarify this.

The 'pixel domain' pertains to the binned image axes.  You have an N-Dimensional image, the pixel coordinate identifies the the cell of the array.  
The 'physical domain' are the physical quantities ( have physical meaning ) that you find as columns in cubes, event lists, and catalogs; or the physical/wcs axes and value of images.  These include position, time, flux, magnitude, temperature, etc.

There has been confusion in the past about the line/relation between Coordinates and Measurements models..
There is certainly a relation between the Measurements and Coordinates models, ( Meas uses Coords ), but one should not not need to read Meas to understand Coords.    In a nutshell, the Coordinates model defines the 'values' and the domain space in which they live.  The Measurements model combines Value and Error to define what we typically see as data/properties in cubes, event lists and catalogs.

**Comment by mcdittmar** [comment]
>Section 4.8, item 2:  MJD/JD and UTC

I think this is a misinterpretation, and there is certainly room to improve that phrasing.
I believe the 3rd bullet is expressing that one should not represent UTC times using JD/MJD, but rather express them as a formatted string (ala ISOTime).

Perhaps a better phrasing for these bullets..
* JD and MJD are dimensionless, though a unit of ’day’ is implied.
* JD and MJD do not imply a time scale; it needs to be provided separately.
* JD and MJD are not recommended for expressing times in UTC since not all UTC days are the same length.  Instead, UTC times are best expressed as a formatted string such as the ISOTime type described in Section 4.10"

**Comment by mcdittmar** [comment]
>Section 4.8, item 6: 
re: A&A cite - yes, this should be "the above cited FITS WCS paper."

That bullet has become a mess.  How about something more generic?
6. What else is there to know?
* Quite a lot!  Complete and accurate Time metadata is extremely important for many IVOA use cases.  We strongly encourage a review of the above cited FITS WCS paper when describing temporal data.

**Comment by mcdittmar** [comment]
>Section 4.13.1: TimeOffset
>o  units of measure

TimeOffset.time is a RealQuantity type, the units are included there.

>o Is there a reason why this is required to be a real number and not an ISO 8601 time interval? 

The vast majority of data we seen represent time offsets as a real number, it is the natural 'type' for this.
The ISOTime type accommodates a very common representation for instants seen in data, but the model is not encouraging adoption of ISO 8601 as a whole.

**Comment by pahjbo** [comment]
I think that ISOTime type is problematic with its 'association' with ISO8601 because

- ISO8601 is definitely using UTC
- something that "looks" like ISO8601 is quite likely going to get passed to a library ISO8601 decoder routine and If you don't use the Z suffix then that routine will end up having the local time offset added to it.

My suggestion would be to 

- drop all mention of ISO8601
- chose a string serialisation that is explicitly forbidden by ISO8601 - perhaps use a different separator character between the Date and Time

_or_

keep the ISO8601 association and add the Z to the string

_or_

Drop the ISOTime type entirely and make ivoa:datetime explicitly have ISO8601 serialization (this is my favourite)

**Comment by mbtaylor** [comment]
ISO8601-like times in the VO are often done as per FITS, as discussed in [DALI 1.1, sec 3.3.3](https://www.ivoa.net/documents/DALI/20170517/REC-DALI-1.1.html#tth_sEc3.3.3).  Since Coords DM is not a DAL service I don't think it's obliged to follow DALI, but it makes sense for consistency.

**Comment by pahjbo** [comment]
> ISO8601-like times in the VO are often done as per FITS, as discussed in [DALI 1.1, sec 3.3.3](https://www.ivoa.net/documents/DALI/20170517/REC-DALI-1.1.html#tth_sEc3.3.3). Since Coords DM is not a DAL service I don't think it's obliged to follow DALI, but it makes sense for consistency.

The problem is that FITS made the wrong call in leaving the Z off (it did not even save any space in headers, so I have no idea why it was thought a good idea) - these data models are working in the environment of relational databases and xml serialisation libraries and if something looks like ISO8601 it is going to get treated as ISO8601 and you have to jump through hoops to keep trying to force the +0 timezone. I suspect that this has not been more of a problem in practice because many people run their astronomical computer systems in the the UTC time zone.

This keeps coming up - see for instance http://mail.ivoa.net/pipermail/dal/2013-November/006505.html and I remember bringing it up in STC 1

**Comment by mcdittmar** [comment]
> ISO8601-like times in the VO are often done as per FITS, as discussed in [DALI 1.1, sec 3.3.3](https://www.ivoa.net/documents/DALI/20170517/REC-DALI-1.1.html#tth_sEc3.3.3). Since Coords DM is not a DAL service I don't think it's obliged to follow DALI, but it makes sense for consistency.

We made a point to be consistent with DALI when doing the ISOTime element.  The text in the "Brief Primer on Time Metadata" was more or less a commentary added by Arnold and I've left that alone for the most part.  

The description of ISOTime object says:  
"The string representation of a datetime value should follow the FITS convention for representing dates (Hanish and Farris et al, 2001). The FITS standard is effectively ISO8601 format without the ’Z’ tag to indicate UTC: YYYY-MM-DD[’T’hh:mm:ss[.SSS]]. The TimeScale is provided in the associated TimeFrame."

The difference from DALI being that the model does not require default interpretation as UTC (since the associated timescale is supposed to do that), where the DALI can since it has a specific usage.

Paul, I understand your point, but I think the VO needs to come up with a strategy if it is to make a change which would conflict with a very prevalent serialization format in our data products.  I think the philosophy has been something like "always check the timescale, and if missing, assume a default appropriate for the context".  In the Coordinates model, there is no specific context.

**Comment by pahjbo** [comment]
> > Section 4.8, item 2:  MJD/JD and UTC
> 
> I think this is a misinterpretation, and there is certainly room to improve that phrasing. I believe the 3rd bullet is expressing that one should not represent UTC times using JD/MJD, but rather express them as a formatted string (ala ISOTime).
> 
> Perhaps a better phrasing for these bullets..
> 
> * JD and MJD are dimensionless, though a unit of ’day’ is implied.
> * JD and MJD do not imply a time scale; it needs to be provided separately.
> * JD and MJD are not recommended for expressing times in UTC since not all UTC days are the same length.  Instead, UTC times are best expressed as a formatted string such as the ISOTime type described in Section 4.10"

This is the converse argument that ISOTime does not really need an arbitrary timescale - UTC is the natural one to use for a string representation. However, it really should not be called ISOTime if it is not an ISO8601 time.

This is also why 

Drop the ISOTime type entirely and make ivoa:datetime explicitly have ISO8601 serialization 

is my favourite solution to this

**Comment by mcdittmar** [comment]
>  However, it really should not be called ISOTime if it is not an ISO8601 time.

I grudgingly agree with this point, FITSTime would be more appropriate.
(grudgingly - because it means a good bit of work for me to change it, and propagate it through all the example files and implementations).

I'll note here that AstroPy has a "TimeISO" class with several sub-types and a "TimeFITS".. this object matches the latter.
I'd hesitate to just make a generic StringTime, since the point of these types is to allow data providers to tell consumers how to interpret the value.  If the value is "2022-04-27T18:53.000" it should be interpreted differently if tagged as an "ISO-8601" time vs a "FITS time".  In this model, we only have one option, which says the format is compatible with ISO8601, but should be interpreted a bit differently.

> 
> This is also why
> Drop the ISOTime type entirely and make ivoa:datetime explicitly have ISO8601 serialization

I don't think this can happen.. ivoa:datetime is not a Coordinate type.  We need this element for the string representation of the Time.. the value (ivoa:datetime) is rather vague in its specification, but would be handled by code which can understand the FITS string format among others like ISO8601.  I don't think the VO is ready to declare that all string formatted datetime-s must be written in ISO8601 format.
